methods = [
    "prends un selfie avec eux", "fais-les manger une chips", "serre leur main",
    "fais-les rire", "chante une chanson ensemble", "donne-leur un petit objet",
    "demande-leur de dire un mot précis", "offre-leur un verre d'eau",
    "demande-leur des directions pour aller quelque part", "convaincs-les de s'asseoir sur une chaise spécifique",
    "demande-leur de deviner un numéro", "partage un fait amusant avec eux",
    "apprends-leur un pas de danse", "fais-leur un high-five", "demande-leur de tenir quelque chose pour toi",
    "fais semblant de les interviewer", "fais-les dessiner un dessin simple",
    "demande-leur de raconter une blague", "demande-leur de t'aider à trouver un objet",
    "demande-leur de se joindre à toi pour une petite promenade", "fais-les imiter un bruit d'animal",
    "joue à pierre-papier-ciseaux avec eux", "montre-leur un tour de magie",
    "demande-leur d'applaudir", "demande-leur de faire un étirement rapide",
    "demande-leur d'identifier une couleur autour de toi", "demande-leur de sourire pour une photo",
    "fais-les fredonner une mélodie", "demande-leur de lire quelque chose à haute voix",
    "partage un salut secret", "demande-leur de faire un petit service pour toi",
    "fais-les compter quelque chose à proximité", "demande-leur de pointer un objet au hasard",
    "demande-leur de complimenter quelqu'un", "demande-leur de te raconter un souvenir amusant",
    "fais-les décrire leur nourriture préférée", "demande-leur d'écrire leur couleur préférée",
    "demande-leur de réciter un virelangue", "demande-leur de faire un petit saut",
    "demande-leur de jouer à un jeu de devinette", "demande-leur de lister trois choses qu'ils aiment",
    "fais semblant de leur remettre un prix", "demande-leur d'imiter ton geste",
    "demande-leur de décrire le temps qu'il fait", "demande-leur de t'aider à réorganiser quelque chose",
    "demande-leur de compter à rebours depuis 10", "demande-leur d'épeler un mot à l'envers",
    "demande-leur de nommer un type de fleur", "demande-leur de décrire un bruit",
    "fais-les plier un avion en papier", "demande-leur de siffler",
    "demande-leur de faire semblant de cueillir un fruit", "demande-leur de toucher quelque chose de doux",
    "demande-leur de se tenir à un endroit spécifique", "demande-leur de faire un pas de danse rapide",
    "demande-leur de dessiner un cercle dans l'air", "demande-leur d'imaginer un scénario",
    "demande-leur de jouer à un jeu d'association de mots", "demande-leur d'identifier une odeur",
    "demande-leur de fermer les yeux pendant 5 secondes", "demande-leur de nommer leur animal préféré",
    "demande-leur d'imiter un personnage célèbre", "demande-leur de tenir l'équilibre sur un pied",
    "demande-leur de faire semblant de lancer une balle", "demande-leur de dire un nombre au hasard",
    "demande-leur d'identifier un bruit à proximité", "demande-leur de toucher quelque chose de froid",
    "demande-leur d'imiter un cri d'oiseau", "demande-leur de décrire un arbre",
    "demande-leur d'imiter un rythme de batterie", "demande-leur d'identifier un fruit",
    "demande-leur de dire l'alphabet à l'envers", "demande-leur de toucher quelque chose de vert",
    "demande-leur de décrire leurs vacances préférées", "demande-leur de battre des mains sur un rythme",
    "demande-leur de faire semblant de tenir un objet invisible", "demande-leur de saluer quelqu'un à proximité",
    "demande-leur de taper du pied", "demande-leur de cligner des yeux rapidement",
    "demande-leur de nommer une personnalité historique", "demande-leur de dessiner une forme avec leur doigt",
    "demande-leur de décrire leur destination de rêve", "demande-leur d'imiter un robot",
    "demande-leur de faire semblant d'être une statue", "demande-leur de partager un fait de culture générale",
    "demande-leur de nommer un type d'arbre", "demande-leur de fredonner une mélodie familière",
    "demande-leur d'imaginer un endroit préféré", "demande-leur de mimer en train de manger un fruit",
    "demande-leur de tapoter leur nez", "demande-leur d'imiter le bruit d'un moteur de voiture",
    "demande-leur de faire un bruit de machine à laver", "demande-leur de faire semblant d'être un super-héros",
    "demande-leur de t'expliquer une blague drôle", "demande-leur de faire semblant de jouer d'un instrument",
    "demande-leur de danser sans musique", "demande-leur de t'enseigner un mot dans une langue étrangère",
    "fais-leur imiter un mouvement d'animal imaginaire", "demande-leur de faire une pirouette",
    "fais-leur raconter une histoire étrange mais vraie", "demande-leur de t'apprendre un tour de magie",
    "demande-leur de mimer une scène de film", "fais-leur énumérer les couleurs d'un arc-en-ciel",
    "demande-leur de trouver un objet rond autour de vous", "demande-leur de faire une danse de robot",
    "demande-leur de te montrer une posture de yoga", "demande-leur de jouer un rôle dans un film imaginaire",
    "demande-leur de raconter un rêve étrange", "demande-leur de faire une grimace", 
    "demande-leur de chanter une chanson des années 90", "fais-leur inventer une nouvelle danse",
    "demande-leur de décrire leur journée parfaite", "demande-leur de montrer un talent caché",
    "demande-leur de faire semblant d'être un cheval", "demande-leur de raconter un fait historique fascinant",
    "demande-leur de deviner un métier au hasard", "demande-leur de dessiner quelque chose avec des yeux fermés",
    "fais-leur imiter un personnage de dessin animé", "demande-leur de réciter une citation célèbre",
    "demande-leur de poser un geste qui les rend heureux", "demande-leur de dire un mot sans prononcer les voyelles",
    "demande-leur de chanter dans une langue qu'ils ne connaissent pas", "demande-leur de mimer leur film préféré",
    "fais-leur inventer un chant de guerre", "demande-leur de raconter une anecdote drôle sur leur enfance",
    "demande-leur de simuler une éruption volcanique", "demande-leur de toucher quelque chose de froid et chaud en même temps",
    "demande-leur de faire une déclaration d'amour à un objet", "demande-leur de dire un poème inventé",
    "demande-leur de sauter sur place en comptant jusqu'à 10", "demande-leur de t'enseigner un mouvement de danse populaire",
    "demande-leur de faire semblant d'être un extraterrestre", "demande-leur de trouver un objet en forme de cœur",
    "fais-leur inventer une blague de mots", "demande-leur de décrire un animal imaginaire",
    "demande-leur de faire une chanson improvisée", "demande-leur de faire le bruit d'une voiture en marche",
    "demande-leur de toucher un objet doux puis rugueux", "fais-leur poser une question existentielle",
    "demande-leur de faire une imitation d'une personne connue", "demande-leur de chanter une chanson à l'envers",
    "demande-leur de jongler avec trois objets imaginaires", "demande-leur de mimer un sportif en plein effort"
]
